<Project Sdk="Microsoft.NET.Sdk">
	
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<ApplicationIcon>Ico.ico</ApplicationIcon>

		<!-- Versionado Semántico (SemVer) y Metadatos de Publicación -->
		<Version>1.1.0</Version>
		<AssemblyVersion>1.1.0.0</AssemblyVersion>
		<FileVersion>1.1.0.0</FileVersion>
		<InformationalVersion>1.1.0</InformationalVersion>
		<Product>EchoCut</Product>
		<Authors>Jorge Silva</Authors>
		<Company>EchoCut</Company>
		<Description>Recortador inteligente y sin pérdidas de silencio final para bibliotecas de audio masivas.</Description>
		<Copyright>Copyright © 2026 Jorge Silva. Licencia GPLv3.</Copyright>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="Ico.ico" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\EchoCut.Core\EchoCut.Core.csproj" />
	</ItemGroup>

</Project>
